---
version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2020.01
  working_directory: ~/ENCODE-DCC/wgbs-pipeline

machine_defaults: &machine_defaults
  machine:
    image: ubuntu-2004:202201-02
  working_directory: ~/ENCODE-DCC/wgbs-pipeline

py37: &py37
  docker:
    - image: circleci/python:3.7.4-stretch
  working_directory: ~/ENCODE-DCC/wgbs-pipeline

make_tag: &make_tag
  name: make docker image tag
  command: |
    echo "export TAG=encodedcc/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}" >> ${BASH_ENV}

commands:
  run_tox:
    description: Install and run tox with a given environment
    parameters:
      toxenv:
        description: The name of the environment as per tox.ini, e.g. py37 or lint
        type: string
      extra_args:
        description: Extra arguments that are consumed only when running pytest
        type: string
        default: ''
    steps:
      - run: sudo pip install tox
      - run: tox -e << parameters.toxenv >> -- << parameters.extra_args >>

  set_environment_variables:
    description: Set docker image env vars for builds and WDL test runs
    steps:
      - run:
          command: |
            echo "export WGBS_DOCKER_IMAGE_TAG=encodedcc/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}_${CIRCLE_WORKFLOW_ID}" >> ${BASH_ENV}

  get_pipeline_version:
    description: get pipeline version from __init__.py
    steps:
      - run:
          command: |
            PIPELINE_VERSION=$(python3 -c "import wgbs_pipeline;print(wgbs_pipeline.__version__)")
            echo "export PIPELINE_VERSION=${PIPELINE_VERSION}" >> ${BASH_ENV}

  install_shellcheck:
    description: Install shellcheck by downloading the binary, don't want to apt-get update
    steps:
      - run: curl -Ls https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz | tar xJ && sudo mv shellcheck-stable/shellcheck
          /usr/local/bin

  add_docker_to_inputs:
    description: Add docker to input JSONs
    steps:
      - run:
          command: |
            for i in tests/unit/json/*.json tests/integration/json/*.json tests/functional/json/*.json; do
              python tests/add_docker_to_input.py $i $WGBS_DOCKER_IMAGE_TAG
            done

jobs:
  lint:
    <<: *py37
    steps:
      - checkout
      - install_shellcheck
      - run_tox:
          toxenv: lint
  test_py37:
    <<: *py37
    steps:
      - checkout
      - run_tox:
          toxenv: py37
  coverage-report:
    <<: *py37
    steps:
      - checkout
      - run_tox:
          toxenv: coverage-report
  test_wdl:
    <<: *machine_defaults
    description: Generic testing protocol for wdl tasks
    parameters:
      tag:
        description: pytest-workflow tag, e.g. functional, integration, test_align
        type: string
      num_parallel_workflows:
        description: Max number of tests to execute in parallel
        type: integer
      resource_class:
        description: The machine resource class to run the test with
        type: string
        default: medium
    resource_class: << parameters.resource_class >>
    steps:
      - checkout
      - set_environment_variables
      - add_docker_to_inputs
      - run:
          name: Run pytest-workflow WDL tests using tox
          command: |
            pyenv install 3.7.0
            pyenv global 3.7.0
            pip install --upgrade pip
            pip install tox
            tox -e wdl -- --tag << parameters.tag >> --wt << parameters.num_parallel_workflows >> --kwd
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - set_environment_variables
      - run: *make_tag
      - run:
          name: build image
          command: |
            source ${BASH_ENV}
            echo "pulling template!"
            docker pull encodedcc/${CIRCLE_PROJECT_REPONAME}:template
            docker login -u=${DOCKERHUB_USER} -p=${DOCKERHUB_PASS}
            docker build . \
              -f Dockerfile \
              --cache-from encodedcc/${CIRCLE_PROJECT_REPONAME}:template \
              -t "${TAG}" \
              -t encodedcc/${CIRCLE_PROJECT_REPONAME}:template
            docker push "${TAG}"
            docker logout
          no_output_timeout: 30m

  push_template:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
      - set_environment_variables
      - get_pipeline_version
      - run: *make_tag
      - run:
          command: |
            source ${BASH_ENV}
            docker pull "${TAG}"
            docker login -u=${DOCKERHUB_USER} -p=${DOCKERHUB_PASS}
            docker tag "${TAG}" encodedcc/${CIRCLE_PROJECT_REPONAME}:template
            docker tag ${TAG} encodedcc/${CIRCLE_PROJECT_REPONAME}:${PIPELINE_VERSION}
            docker push encodedcc/${CIRCLE_PROJECT_REPONAME}:${PIPELINE_VERSION}
            docker push encodedcc/${CIRCLE_PROJECT_REPONAME}:template
            docker logout
          no_output_timeout: 30m

# Define workflow here
workflows:
  version: 2
  build_workflow:
    jobs:
      - build
      - lint
      - coverage-report
      - test_py37:
          requires:
            - build
            - lint
      - test_wdl:
          name: test_wdl_unit
          tag: unit
          num_parallel_workflows: 8
          requires:
            - build
            - lint
      - test_wdl:
          name: test_wdl_integration
          resource_class: large
          tag: integration
          num_parallel_workflows: 12
          requires:
            - build
            - lint
      - test_wdl:
          name: test_wdl_functional
          resource_class: large
          tag: functional
          num_parallel_workflows: 8
          requires:
            - build
            - lint
      - push_template:
          requires:
            - build
            - lint
            - coverage-report
            - test_py37
            - test_wdl_unit
            - test_wdl_integration
            - test_wdl_functional
          filters:
            branches:
              only:
                - dev
                - master
