__title__ = "wgbs-pipeline"
__version__ = "1.1.1"
__description__ = "Python scripts required for running ENCODE WGBS pipeline."
__url__ = "https://github.com/ENCODE-DCC/wgbs-pipeline"
__uri__ = __url__
__author__ = "Paul Sud"
__email__ = "encode-help@lists.stanford.edu"
__license__ = "MIT"
__copyright__ = "Copyright (c) 2020 ENCODE DCC"
